// export by github.com/goplus/igop/cmd/qexp

//go:build go1.18
// +build go1.18

package date

import (
	q "golang.org/x/text/date"

	"go/constant"
	"reflect"

	"github.com/goplus/igop"
)

func init() {
	igop.RegisterPackage(&igop.Package{
		Name: "date",
		Path: "golang.org/x/text/date",
		Deps: map[string]string{
			"golang.org/x/text/internal/cldrtree": "cldrtree",
		},
		Interfaces:  map[string]reflect.Type{},
		NamedTypes:  map[string]reflect.Type{},
		AliasTypes:  map[string]reflect.Type{},
		Vars:        map[string]reflect.Value{},
		Funcs:       map[string]reflect.Value{},
		TypedConsts: map[string]igop.TypedConst{},
		UntypedConsts: map[string]igop.UntypedConst{
			"Acre":                     {"untyped int", constant.MakeInt64(int64(q.Acre))},
			"Afghanistan":              {"untyped int", constant.MakeInt64(int64(q.Afghanistan))},
			"Africa_Central":           {"untyped int", constant.MakeInt64(int64(q.Africa_Central))},
			"Africa_Eastern":           {"untyped int", constant.MakeInt64(int64(q.Africa_Eastern))},
			"Africa_Southern":          {"untyped int", constant.MakeInt64(int64(q.Africa_Southern))},
			"Africa_Western":           {"untyped int", constant.MakeInt64(int64(q.Africa_Western))},
			"Alaska":                   {"untyped int", constant.MakeInt64(int64(q.Alaska))},
			"Almaty":                   {"untyped int", constant.MakeInt64(int64(q.Almaty))},
			"Amazon":                   {"untyped int", constant.MakeInt64(int64(q.Amazon))},
			"America_Central":          {"untyped int", constant.MakeInt64(int64(q.America_Central))},
			"America_Eastern":          {"untyped int", constant.MakeInt64(int64(q.America_Eastern))},
			"America_Mountain":         {"untyped int", constant.MakeInt64(int64(q.America_Mountain))},
			"America_Pacific":          {"untyped int", constant.MakeInt64(int64(q.America_Pacific))},
			"Anadyr":                   {"untyped int", constant.MakeInt64(int64(q.Anadyr))},
			"Apia":                     {"untyped int", constant.MakeInt64(int64(q.Apia))},
			"Aqtau":                    {"untyped int", constant.MakeInt64(int64(q.Aqtau))},
			"Aqtobe":                   {"untyped int", constant.MakeInt64(int64(q.Aqtobe))},
			"Arabian":                  {"untyped int", constant.MakeInt64(int64(q.Arabian))},
			"Argentina":                {"untyped int", constant.MakeInt64(int64(q.Argentina))},
			"Argentina_Western":        {"untyped int", constant.MakeInt64(int64(q.Argentina_Western))},
			"Armenia":                  {"untyped int", constant.MakeInt64(int64(q.Armenia))},
			"Atlantic":                 {"untyped int", constant.MakeInt64(int64(q.Atlantic))},
			"Australia_Central":        {"untyped int", constant.MakeInt64(int64(q.Australia_Central))},
			"Australia_CentralWestern": {"untyped int", constant.MakeInt64(int64(q.Australia_CentralWestern))},
			"Australia_Eastern":        {"untyped int", constant.MakeInt64(int64(q.Australia_Eastern))},
			"Australia_Western":        {"untyped int", constant.MakeInt64(int64(q.Australia_Western))},
			"Azerbaijan":               {"untyped int", constant.MakeInt64(int64(q.Azerbaijan))},
			"Azores":                   {"untyped int", constant.MakeInt64(int64(q.Azores))},
			"Bangladesh":               {"untyped int", constant.MakeInt64(int64(q.Bangladesh))},
			"Bhutan":                   {"untyped int", constant.MakeInt64(int64(q.Bhutan))},
			"Bolivia":                  {"untyped int", constant.MakeInt64(int64(q.Bolivia))},
			"Brasilia":                 {"untyped int", constant.MakeInt64(int64(q.Brasilia))},
			"Brunei":                   {"untyped int", constant.MakeInt64(int64(q.Brunei))},
			"CLDRVersion":              {"untyped string", constant.MakeString(string(q.CLDRVersion))},
			"Cape_Verde":               {"untyped int", constant.MakeInt64(int64(q.Cape_Verde))},
			"Casey":                    {"untyped int", constant.MakeInt64(int64(q.Casey))},
			"Chamorro":                 {"untyped int", constant.MakeInt64(int64(q.Chamorro))},
			"Chatham":                  {"untyped int", constant.MakeInt64(int64(q.Chatham))},
			"Chile":                    {"untyped int", constant.MakeInt64(int64(q.Chile))},
			"China":                    {"untyped int", constant.MakeInt64(int64(q.China))},
			"Choibalsan":               {"untyped int", constant.MakeInt64(int64(q.Choibalsan))},
			"Christmas":                {"untyped int", constant.MakeInt64(int64(q.Christmas))},
			"Cocos":                    {"untyped int", constant.MakeInt64(int64(q.Cocos))},
			"Colombia":                 {"untyped int", constant.MakeInt64(int64(q.Colombia))},
			"Cook":                     {"untyped int", constant.MakeInt64(int64(q.Cook))},
			"Cuba":                     {"untyped int", constant.MakeInt64(int64(q.Cuba))},
			"Davis":                    {"untyped int", constant.MakeInt64(int64(q.Davis))},
			"DumontDUrville":           {"untyped int", constant.MakeInt64(int64(q.DumontDUrville))},
			"East_Timor":               {"untyped int", constant.MakeInt64(int64(q.East_Timor))},
			"Easter":                   {"untyped int", constant.MakeInt64(int64(q.Easter))},
			"Ecuador":                  {"untyped int", constant.MakeInt64(int64(q.Ecuador))},
			"EtcUTC":                   {"untyped int", constant.MakeInt64(int64(q.EtcUTC))},
			"EuropeDublin":             {"untyped int", constant.MakeInt64(int64(q.EuropeDublin))},
			"EuropeLondon":             {"untyped int", constant.MakeInt64(int64(q.EuropeLondon))},
			"Europe_Central":           {"untyped int", constant.MakeInt64(int64(q.Europe_Central))},
			"Europe_Eastern":           {"untyped int", constant.MakeInt64(int64(q.Europe_Eastern))},
			"Europe_Further_Eastern":   {"untyped int", constant.MakeInt64(int64(q.Europe_Further_Eastern))},
			"Europe_Western":           {"untyped int", constant.MakeInt64(int64(q.Europe_Western))},
			"Falkland":                 {"untyped int", constant.MakeInt64(int64(q.Falkland))},
			"Fiji":                     {"untyped int", constant.MakeInt64(int64(q.Fiji))},
			"French_Guiana":            {"untyped int", constant.MakeInt64(int64(q.French_Guiana))},
			"French_Southern":          {"untyped int", constant.MakeInt64(int64(q.French_Southern))},
			"GMT":                      {"untyped int", constant.MakeInt64(int64(q.GMT))},
			"Galapagos":                {"untyped int", constant.MakeInt64(int64(q.Galapagos))},
			"Gambier":                  {"untyped int", constant.MakeInt64(int64(q.Gambier))},
			"Georgia":                  {"untyped int", constant.MakeInt64(int64(q.Georgia))},
			"Gilbert_Islands":          {"untyped int", constant.MakeInt64(int64(q.Gilbert_Islands))},
			"Greenland_Eastern":        {"untyped int", constant.MakeInt64(int64(q.Greenland_Eastern))},
			"Greenland_Western":        {"untyped int", constant.MakeInt64(int64(q.Greenland_Western))},
			"Guam":                     {"untyped int", constant.MakeInt64(int64(q.Guam))},
			"Gulf":                     {"untyped int", constant.MakeInt64(int64(q.Gulf))},
			"Guyana":                   {"untyped int", constant.MakeInt64(int64(q.Guyana))},
			"Hawaii_Aleutian":          {"untyped int", constant.MakeInt64(int64(q.Hawaii_Aleutian))},
			"Hong_Kong":                {"untyped int", constant.MakeInt64(int64(q.Hong_Kong))},
			"Hovd":                     {"untyped int", constant.MakeInt64(int64(q.Hovd))},
			"India":                    {"untyped int", constant.MakeInt64(int64(q.India))},
			"Indian_Ocean":             {"untyped int", constant.MakeInt64(int64(q.Indian_Ocean))},
			"Indochina":                {"untyped int", constant.MakeInt64(int64(q.Indochina))},
			"Indonesia_Central":        {"untyped int", constant.MakeInt64(int64(q.Indonesia_Central))},
			"Indonesia_Eastern":        {"untyped int", constant.MakeInt64(int64(q.Indonesia_Eastern))},
			"Indonesia_Western":        {"untyped int", constant.MakeInt64(int64(q.Indonesia_Western))},
			"Iran":                     {"untyped int", constant.MakeInt64(int64(q.Iran))},
			"Irkutsk":                  {"untyped int", constant.MakeInt64(int64(q.Irkutsk))},
			"Israel":                   {"untyped int", constant.MakeInt64(int64(q.Israel))},
			"Japan":                    {"untyped int", constant.MakeInt64(int64(q.Japan))},
			"Kamchatka":                {"untyped int", constant.MakeInt64(int64(q.Kamchatka))},
			"Kazakhstan_Eastern":       {"untyped int", constant.MakeInt64(int64(q.Kazakhstan_Eastern))},
			"Kazakhstan_Western":       {"untyped int", constant.MakeInt64(int64(q.Kazakhstan_Western))},
			"Korea":                    {"untyped int", constant.MakeInt64(int64(q.Korea))},
			"Kosrae":                   {"untyped int", constant.MakeInt64(int64(q.Kosrae))},
			"Krasnoyarsk":              {"untyped int", constant.MakeInt64(int64(q.Krasnoyarsk))},
			"Kyrgystan":                {"untyped int", constant.MakeInt64(int64(q.Kyrgystan))},
			"Lanka":                    {"untyped int", constant.MakeInt64(int64(q.Lanka))},
			"Line_Islands":             {"untyped int", constant.MakeInt64(int64(q.Line_Islands))},
			"Lord_Howe":                {"untyped int", constant.MakeInt64(int64(q.Lord_Howe))},
			"Macau":                    {"untyped int", constant.MakeInt64(int64(q.Macau))},
			"Macquarie":                {"untyped int", constant.MakeInt64(int64(q.Macquarie))},
			"Magadan":                  {"untyped int", constant.MakeInt64(int64(q.Magadan))},
			"Malaysia":                 {"untyped int", constant.MakeInt64(int64(q.Malaysia))},
			"Maldives":                 {"untyped int", constant.MakeInt64(int64(q.Maldives))},
			"Marquesas":                {"untyped int", constant.MakeInt64(int64(q.Marquesas))},
			"Marshall_Islands":         {"untyped int", constant.MakeInt64(int64(q.Marshall_Islands))},
			"Mauritius":                {"untyped int", constant.MakeInt64(int64(q.Mauritius))},
			"Mawson":                   {"untyped int", constant.MakeInt64(int64(q.Mawson))},
			"Mexico_Northwest":         {"untyped int", constant.MakeInt64(int64(q.Mexico_Northwest))},
			"Mexico_Pacific":           {"untyped int", constant.MakeInt64(int64(q.Mexico_Pacific))},
			"Mongolia":                 {"untyped int", constant.MakeInt64(int64(q.Mongolia))},
			"Moscow":                   {"untyped int", constant.MakeInt64(int64(q.Moscow))},
			"Myanmar":                  {"untyped int", constant.MakeInt64(int64(q.Myanmar))},
			"Nauru":                    {"untyped int", constant.MakeInt64(int64(q.Nauru))},
			"Nepal":                    {"untyped int", constant.MakeInt64(int64(q.Nepal))},
			"New_Caledonia":            {"untyped int", constant.MakeInt64(int64(q.New_Caledonia))},
			"New_Zealand":              {"untyped int", constant.MakeInt64(int64(q.New_Zealand))},
			"Newfoundland":             {"untyped int", constant.MakeInt64(int64(q.Newfoundland))},
			"Niue":                     {"untyped int", constant.MakeInt64(int64(q.Niue))},
			"Norfolk":                  {"untyped int", constant.MakeInt64(int64(q.Norfolk))},
			"Noronha":                  {"untyped int", constant.MakeInt64(int64(q.Noronha))},
			"North_Mariana":            {"untyped int", constant.MakeInt64(int64(q.North_Mariana))},
			"Novosibirsk":              {"untyped int", constant.MakeInt64(int64(q.Novosibirsk))},
			"Omsk":                     {"untyped int", constant.MakeInt64(int64(q.Omsk))},
			"PacificHonolulu":          {"untyped int", constant.MakeInt64(int64(q.PacificHonolulu))},
			"Pakistan":                 {"untyped int", constant.MakeInt64(int64(q.Pakistan))},
			"Palau":                    {"untyped int", constant.MakeInt64(int64(q.Palau))},
			"Papua_New_Guinea":         {"untyped int", constant.MakeInt64(int64(q.Papua_New_Guinea))},
			"Paraguay":                 {"untyped int", constant.MakeInt64(int64(q.Paraguay))},
			"Peru":                     {"untyped int", constant.MakeInt64(int64(q.Peru))},
			"Philippines":              {"untyped int", constant.MakeInt64(int64(q.Philippines))},
			"Phoenix_Islands":          {"untyped int", constant.MakeInt64(int64(q.Phoenix_Islands))},
			"Pierre_Miquelon":          {"untyped int", constant.MakeInt64(int64(q.Pierre_Miquelon))},
			"Pitcairn":                 {"untyped int", constant.MakeInt64(int64(q.Pitcairn))},
			"Ponape":                   {"untyped int", constant.MakeInt64(int64(q.Ponape))},
			"Pyongyang":                {"untyped int", constant.MakeInt64(int64(q.Pyongyang))},
			"Qyzylorda":                {"untyped int", constant.MakeInt64(int64(q.Qyzylorda))},
			"Reunion":                  {"untyped int", constant.MakeInt64(int64(q.Reunion))},
			"Rothera":                  {"untyped int", constant.MakeInt64(int64(q.Rothera))},
			"Sakhalin":                 {"untyped int", constant.MakeInt64(int64(q.Sakhalin))},
			"Samara":                   {"untyped int", constant.MakeInt64(int64(q.Samara))},
			"Samoa":                    {"untyped int", constant.MakeInt64(int64(q.Samoa))},
			"Seychelles":               {"untyped int", constant.MakeInt64(int64(q.Seychelles))},
			"Singapore":                {"untyped int", constant.MakeInt64(int64(q.Singapore))},
			"Solomon":                  {"untyped int", constant.MakeInt64(int64(q.Solomon))},
			"South_Georgia":            {"untyped int", constant.MakeInt64(int64(q.South_Georgia))},
			"Suriname":                 {"untyped int", constant.MakeInt64(int64(q.Suriname))},
			"Syowa":                    {"untyped int", constant.MakeInt64(int64(q.Syowa))},
			"Tahiti":                   {"untyped int", constant.MakeInt64(int64(q.Tahiti))},
			"Taipei":                   {"untyped int", constant.MakeInt64(int64(q.Taipei))},
			"Tajikistan":               {"untyped int", constant.MakeInt64(int64(q.Tajikistan))},
			"Tokelau":                  {"untyped int", constant.MakeInt64(int64(q.Tokelau))},
			"Tonga":                    {"untyped int", constant.MakeInt64(int64(q.Tonga))},
			"Truk":                     {"untyped int", constant.MakeInt64(int64(q.Truk))},
			"Turkmenistan":             {"untyped int", constant.MakeInt64(int64(q.Turkmenistan))},
			"Tuvalu":                   {"untyped int", constant.MakeInt64(int64(q.Tuvalu))},
			"Uruguay":                  {"untyped int", constant.MakeInt64(int64(q.Uruguay))},
			"Uzbekistan":               {"untyped int", constant.MakeInt64(int64(q.Uzbekistan))},
			"Vanuatu":                  {"untyped int", constant.MakeInt64(int64(q.Vanuatu))},
			"Venezuela":                {"untyped int", constant.MakeInt64(int64(q.Venezuela))},
			"Vladivostok":              {"untyped int", constant.MakeInt64(int64(q.Vladivostok))},
			"Volgograd":                {"untyped int", constant.MakeInt64(int64(q.Volgograd))},
			"Vostok":                   {"untyped int", constant.MakeInt64(int64(q.Vostok))},
			"Wake":                     {"untyped int", constant.MakeInt64(int64(q.Wake))},
			"Wallis":                   {"untyped int", constant.MakeInt64(int64(q.Wallis))},
			"Yakutsk":                  {"untyped int", constant.MakeInt64(int64(q.Yakutsk))},
			"Yekaterinburg":            {"untyped int", constant.MakeInt64(int64(q.Yekaterinburg))},
		},
	})
}
